export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as Unlock } from './Unlock'
export { default as Platform } from './Platform'
// export { default as KeyFeatures } from './KeyFeatures'
// export { default as SupportedCrypto } from './SupportedCrypto'
export { default as PoweredByBSC } from './PoweredByBSC'
export { default as SfuelToken } from './SfuelToken'
export { default as SfuelFeatures } from './SfuelFeatures'
export { default as Team } from './Team'
export { default as Roadmap } from './Roadmap'
export { default as Exchanges } from './Exchanges'
export { default as OnlineCommunities } from './OnlineCommunities'
// export { default as Founders } from './Founders'
// export { default as Newsletter } from './Newsletter'
// export { default as Newsletter } from './Newsletter'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'